"""add wallet and asset

Revision ID: 4762f3f90edb
Revises: ff6c7d39d0c7
Create Date: 2025-10-22 17:26:40.728656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4762f3f90edb'
down_revision: Union[str, Sequence[str], None] = 'ff6c7d39d0c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('network', sa.Enum('ETHEREUM', 'SEPOLIA', 'POLYGON', 'BSC', 'AVALANCHE', name='assetnetworktypeenum'), nullable=False),
    sa.Column('asset_type', sa.Enum('NATIVE', 'ERC20', 'ERC721', name='assettypeenum'), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('private_key', sa.LargeBinary(), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=100, scale=0), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    op.drop_table('assets')
    # ### end Alembic commands ###
