"""update transaction hash

Revision ID: e6ac54354d1a
Revises: f11b0971aeff
Create Date: 2025-11-05 12:47:19.765691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6ac54354d1a'
down_revision: Union[str, Sequence[str], None] = 'f11b0971aeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('transactions_transaction_hash_key'), 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('transactions_transaction_hash_key'), 'transactions', ['transaction_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
