"""update wallet

Revision ID: fce6551bf8d0
Revises: 4762f3f90edb
Create Date: 2025-10-22 18:14:55.570247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce6551bf8d0'
down_revision: Union[str, Sequence[str], None] = '4762f3f90edb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('wallets_user_id_fkey'), 'wallets', type_='foreignkey')
    op.create_foreign_key(None, 'wallets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallets', type_='foreignkey')
    op.create_foreign_key(op.f('wallets_user_id_fkey'), 'wallets', 'assets', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
